### PR TITLE
Fix bugs

### LINKED ISSUE #107: find cmd unexpected exception
there's also uncaught exceptions if inputs like "find r/" or "find n/" are entered

Image

### LINKED ISSUE #108: find gibberish returns everything
Not supposed to be the case should return 0 contacts

### PR DESCRIPTION
**Pull request by Ma-Yirui**
closes #107 and closes #108

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -34,16 +36,41 @@ public FindCommand parse(String args) throws ParseException {
...
 
         List<String> name = argMultimap.getValue(PREFIX_NAME)
-                .map(value -> Arrays.asList(value.split("\\s+")))
+                .map(value -> Arrays.stream(value.split("\\s+"))
+                        .filter(part -> !part.isEmpty())
+                        .map(part -> {
+                            try {
+                                return ParserUtil.parseName(part).fullName;
+                            } catch (ParseException e) {
+                                throw new RuntimeException(e);
```
Comment (Partillay791) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Perhaps a ParseException object should be re-thrown here instead?

**Review by Partillay791 — COMMENTED** [review]
lgtm overall, just some minor doubts

**Comment by Ma-Yirui** [comment]
closes #117

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java (hunk 1 above)
Comment (Partillay791) [reply src/main/java/seedu/address/logic/parser/FindCommandParser.java]: noted!
